# -*- coding: utf-8 -*-
"""TESLA_BYD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZpRU2_akt73DTwCO7sLx9PW1Nvae9Pi

##. 1 Baixando Bibliotecas
"""

import pandas as pd

import yfinance as yf

import matplotlib.pyplot as plt

import numpy as np

import os

pip install sweetviz

pip install pandas-profiling

import sweetviz as sv

"""## .2 Extraindo Dados"""

tesla = yf.download('TSLA', start='2015-01-01', end='2024-01-01')

byd = yf.download('BYDDY', start='2015-01-01', end='2024-01-01')

byd.columns = byd.columns.droplevel(1)

tesla.columns = tesla.columns.droplevel(1)

byd.index = byd.index.date

tesla.index = tesla.index.date

tesla.columns.name = None

tesla.reset_index(inplace = True)

tesla.rename(columns = {'index':'Date','Adj Close':'TESLA','Close':'Close_TESLA','Open':'Open_TESLA'}, inplace = True)

byd.columns.name = None

byd.reset_index(inplace = True)

byd.rename(columns = {'index':'Date','Adj Close':'BYD','Close':'Close_BYD','Open':'Open_BYD'}, inplace = True)

byd

tesla

novo_df = pd.merge(byd,tesla, how = 'inner', on = 'Date')

cotacao1 = novo_df[['BYD','TESLA']]

cotacao2 = novo_df[['Date','Close_BYD','Close_TESLA']]

print(cotacao2)

close_tesla = novo_df[['Date','Close_TESLA']]

close_byd = novo_df[['Date', 'Close_BYD']]

print(close_tesla)

cotacao2.plot('Date');

# pd.set_option('display.max_rows', None)

pd.reset_option('display.max_rows')

valores_Hclose2_tesla = close_tesla.nlargest(20,'Close_TESLA')

valores_95close_tesla = close_tesla[close_tesla['Close_TESLA'] >= 302]

valores_5close_tesla = close_tesla[close_tesla['Close_TESLA'] <= 13]

print(valores_5close_tesla)

print(valores_95close_tesla)

valores_Hclose_byd2 = close_byd.nlargest(25,'Close_BYD')

valores_95close_byd = close_byd[close_byd['Close_BYD'] >= 69.6]

valores_5close_byd = close_byd[close_byd['Close_BYD'] <= 9.3]

print(valores_5close_byd)

print(valores_95close_byd)

"""## .3 Gerando relatorio"""

relatorio = sv.analyze(cotacao2)

relatorio.show_html('RelatorioXX_TESLA_BYD.html')

